// app/page.tsx
export default function Home() {
	return (
		<div className='grid h-full w-full grid-cols-1 grid-rows-1 place-items-center'>
			<div className='col-span-1 text-center'>
				<h1 className='text-2xl text-white lg:text-3xl'>Al-Amin Firdows</h1>

				<div className='mt-4 text-zinc-400'>
					<ul className='inline-flex space-x-6'>
						<li>PHP Coder</li>
						<li>Laravel Developer</li>
						<li>Problem Solver</li>
					</ul>
				</div>
			</div>
		</div>
	);
}

// src/App.svelte
<script>
</script>

<div class="grid grid-cols-1 h-full w-full place-items-center grid-rows-1">
    <div class="col-span-1 text-center">
        <h1 class="text-white text-2xl lg:text-3xl">Al-Amin Firdows</h1>

        <div class="text-zinc-400 mt-4">
            <ul class="inline-flex space-x-6">
                <li>PHP Coder</li>
                <li>Laravel Developer</li>
                <li>Problem Solver</li>
            </ul>
        </div>
    </div>
</div>
